#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

#include "common/common_ops.h"

#define PIC_HEIGHT 40
#define PIC_WIDTH 72
#define BUF_LEN 360

const char* picture[PIC_HEIGHT] = {
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWIIIIIIIIIIIWWWWIWWIIIIIIIIIIIIIIIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWIWWWWWWWWWWIWWWWIWIWWWWWWWWWWWWWWIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWIWWWWWWWWWWWIWWWWIIWWWWWWWWWWWWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWIWWWWWWWWWWWWIIIIIIWWWWWWWWWWWWWWIWIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWIWWIWWWIIWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIIWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIIWWWWWWWWWWWWWWWWWWWWWIWWWIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
};

char buf[BUF_LEN];

void fill_buf(void) {
    int buf_i, col_i, line_i, bit_i;
    char buf_byte;
    col_i = 0;
    line_i = 0;
    for (buf_i = 0; buf_i < BUF_LEN; buf_i++) {
        buf_byte = 0;
        for (bit_i = 0; bit_i < 8; bit_i++) {
            buf_byte = buf_byte << 1;
            if (picture[line_i][col_i] == 'I') {
                buf_byte |= 1;
            }
            col_i++;
            if (col_i == PIC_WIDTH) {
                col_i = 0;
                line_i += 1;
            }
        }
        buf[buf_i] = buf_byte;
    }
}

int main() {
    if (init_video_params(40)) {
        puts("Couldn't extract display parameters.");
        goto fault;
    }

    int simple;

    fill_buf();
    simple = open("/dev/duel2", O_WRONLY);
    if (simple < 0) {
        puts("The file did not open.");
        goto fault;
    }
    if (360 != write(simple, buf, 360)) {
        puts("Couldn't write 360 bytes.");
        close(simple);
        goto fault;
    }
    close(simple);

    puts("Success");
    return 0;
fault:
    puts("Failure");
    return 1;
}