#include <fcntl.h>
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>

#define PIC_HEIGHT 40
#define PIC_WIDTH 72
#define BUF_LEN 360

const char* picture[PIC_HEIGHT] = {
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWIIIIIIIIIIIWWWWIWWIIIIIIIIIIIIIIIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWIWWWWWWWWWWIWWWWIWIWWWWWWWWWWWWWWIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWIWWWWWWWWWWWIWWWWIIWWWWWWWWWWWWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWIWWWWWWWWWWWWIIIIIIWWWWWWWWWWWWWWIWIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWIWWIWWWIIWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIIWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIIWWWWWWWWWWWWWWWWWWWWWIWWWIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
};

char buf[BUF_LEN];

void fill_buf(void) {
    int buf_i, col_i, line_i, bit_i;
    char buf_byte;
    col_i = 0;
    line_i = 0;
    for (buf_i = 0; buf_i < BUF_LEN; buf_i++) {
        buf_byte = 0;
        for (bit_i = 0; bit_i < 8; bit_i++) {
            buf_byte = buf_byte >> 1;
            if (picture[line_i][col_i] == 'I') {
                buf_byte |= 0x80;
            }
            line_i++;
        }
        buf[buf_i] = buf_byte;
        line_i -= 8;
        col_i += 1;
        if (col_i == PIC_WIDTH) {
            col_i = 0;
            line_i += 8;
        }
    }
}

int main(int argc, const char* argv[]) {
    int fast;

    fill_buf();
    fast = open("/dev/duel1", O_WRONLY);
    if (fast < 0) {
        puts("The file did not open.");
        goto fault;
    }
    if (360 != write(fast, buf, 360)) {
        puts("Couldn't write 360 bytes.");
        close(fast);
        goto fault;
    }
    close(fast);

    puts("Success");
    return 0;
fault:
    puts("Failure");
    return 1;
}