#include <stdio.h>

#define PIC_HEIGHT 40
#define PIC_WIDTH 72

const char* picture[PIC_HEIGHT] = {
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIIIIIIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWIWWWWIWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWIIIIIIIIIIIWWWWIWWIIIIIIIIIIIIIIIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWIWWWWWWWWWWIWWWWIWIWWWWWWWWWWWWWWIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWIWWWWWWWWWWWIWWWWIIWWWWWWWWWWWWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWIWWWWWWWWWWWWIIIIIIWWWWWWWWWWWWWWIWIIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIWIWIWWWIWIWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWIWWIWWWIIWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWIIWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWIWWWIWIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIWWWIIWWWWWWWWWWWWWWWWWWWWWIWWWIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWIIIIIWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
};

int main(int argc, const char* argv[]) {
    return 0;
}